<?php

return [
    [
        'Azienda'=> 'Trenitalia',
        'Stazione_di_partenza' => 'Palermo Centrale',
        'Stazione_di_arrivo' => 'Palermo Notarb.',
        'Orario_di_partenza' => '08:05',
        'Orario_di_arrivo' => '08:35',
        'Codice_Treno' => '454647',
        'Numero_Carrozze' => '20',
        'In_orario' => true,
        'Cancellato' => false,
    ],
    [
        'Azienda'=> 'Trenitalia',
        'Stazione_di_partenza' => 'Palermo Centrale',
        'Stazione_di_arrivo' => 'Palermo Mondello',
        'Orario_di_partenza' => '09:05',
        'Orario_di_arrivo' => '09:55',
        'Codice_Treno' => '454698',
        'Numero_Carrozze' => '17',
        'In_orario' => false,
        'Cancellato' => false,
    ],
    [
        'Azienda'=> 'Trenitalia',
        'Stazione_di_partenza' => 'Palermo Notarbartolo',
        'Stazione_di_arrivo' => 'Palermo Centrale',
        'Orario_di_partenza' => '10:05',
        'Orario_di_arrivo' => '10:35',
        'Codice_Treno' => '544647',
        'Numero_Carrozze' => '10',
        'In_orario' => true,
        'Cancellato' => true,
    ],
    [
        'Azienda'=> 'Trenitalia',
        'Stazione_di_partenza' => 'Palermo Mondello',
        'Stazione_di_arrivo' => 'Palermo Centrale',
        'Orario_di_partenza' => '17:15',
        'Orario_di_arrivo' => '18.55',
        'Codice_Treno' => '454636',
        'Numero_Carrozze' => '17',
        'In_orario' => false,
        'Cancellato' => false,
    ],
];